#!/bin/sh

# script/update - updates dependencies after a repo update

# exit on sub-module failure
set -e

cd "$(dirname "$0")/.."

# --------

echo "Updating..."

sh script/bootstrap

echo "Done updating!"

# --------
